### ISSUE TITLE
Expects package.json and config.js to both be in the baseURL directory

### ISSUE THREAD

**Issue by greylurk** [crstffr/jspm-bundler#13]
I have a project with the following structure:

```
.
├── package.json
├── gulpfile.js
└── src
    ├── index.html
    └── js
        ├── config.js
        ├── .
        ├── .
        ├── .
        └── jspm_packages
```

If I set "baseURL" in the bundler config inside gulpfile.js to "src/js", I get an error ` Error: Package.json file has not been initialized by jspm before. Run jspm init first.`

If I set "baseURL" in the bundler config to ".", to pick up the package.json, I get an error `Error: Cannot find module '/home/greylurk/project/config.js'`

**Comment by crstffr** [comment]
Thanks Adam for the bug report.  I'll have to take a look.  For now my recommendation is to use the previous version [v0.1.9](https://github.com/crstffr/jspm-bundler/releases/tag/v0.1.9) until I can resolve this.

**Comment by crstffr** [comment]
Finally taking a look at this - many many months later.

**Comment by crstffr** [comment]
I believe I've fixed this.  I added a ```packagePath``` option that is different than the ```baseURL```.  I set a sensible default for ```packagePath``` as the root folder (commonly where you'd find your ```package.json``` file.  

According to your project description above, you'd set your ```baseURL``` to ```src/js``` and that should be it.  (If your project even uses this bundler anymore).
